#!/usr/local/bin/tcsh

cd $HOME/weddingcake_alignment/run
. /nfs/cleo3/scripts/cleo3defs
c3rel cleo3_Pass2_Mar26_2002

cat > tmp/first4.tcl << EOF

default prompt off
exception continueEventLoop on

# module sel LoadHbook4MModule
module sel HbookHistogramModule
hbook file first4.rzn
hbook init

module sel CorbaModule
corba init
module sel ConstantsModule
constants in \$env(C3_CONST) meta Offline MetaListRetrieval
constants in \$env(C3_CONST) meta Online MetaListRetrieval
constants in \$env(C3_CONST) meta CesrOffset MetaListRetrieval
constants in \$env(C3_CONST) meta BaseGeometry MetaListRetrieval
constants in \$env(C3_CONST) meta RunByRun MetaListRetrieval
constants in \$env(C3_CONST) meta Alignment MetaListRetrieval
constants in \$env(C3_CONST) meta FieldMap MetaListRetrieval

source_format sel AsciiSourceFormat
file in \$env(C3_DATA)/material.asc basegeometry

source_format sel SVHybridEfficiencyFileSourceFormat
file in normal.svhybridefficiency

source_format sel PDSSourceFormat
source create pdschain
file add pdschain ../dafedir/april_tracks4.pds beginrun event startrun endrun
source activate pdschain beginrun event startrun endrun

prod sel ADRGeomProd
prod sel DRGeom
prod sel MagFieldProd
param MagFieldProd alwaysUseDefault true
param MagFieldProd defaultHallProbeReading 1.4944
prod sel NavigationProd
prod sel TrackDeliveryProd
prod sel SeedToTRTrackProd
prod sel DualTrackHelicesProd
prod sel DBEventHeaderProd
proc sel ../build_SunOS/shlib/CakeAlign

report level ERROR
go 5342
summary
hbook terminate
exit

EOF

suez -f tmp/first4.tcl > $USER_TMP/first4.log
