*
* $Id: sffixdo.inc,v 1.1.1.1 1998/02/06 19:11:50 dpp Exp $
*
* $Log: sffixdo.inc,v $
* Revision 1.1.1.1  1998/02/06 19:11:50  dpp
* DOIT first release.
*
* Revision 1.1.1.1  1997/04/30 12:31:41  clib
* Developmental version of DUET.
*
* Revision 1.1.1.1  1994/10/08 01:01:13  zfiles
* first version of doit in CVS
*
*
* SFFIX DUCUMENTATION
*
* sffixdo.inc
*
C...... STEP FIND FIXES TO THE GEOMETRY
C /STEPF1/..........FIX TO THE PHI OFFSETS OF THE LAYERS
C FFIXSF...PHI_FIX_SF
* ------------------------------------------
#include "doit/duseq/duseqd.inc"
