*
* $Id: sfgkspd.inc,v 1.1.1.1 1998/02/06 19:11:50 dpp Exp $
*
* $Log: sfgkspd.inc,v $
* Revision 1.1.1.1  1998/02/06 19:11:50  dpp
* DOIT first release.
*
* Revision 1.1.1.1  1997/04/30 12:31:42  clib
* Developmental version of DUET.
*
* Revision 1.1.1.1  1994/10/08 01:01:11  zfiles
* first version of doit in CVS
*
*
*CMZ :  5.54/15 11/09/91  17.14.29  by  Dan Peterson
*CMZ :  3.01/01 23/03/90  12.38.36  by  Dan Peterson
*-- Author :
* SFGKSP DOCUMENTATION
* ------------------------------------------
#include "doit/duseq/duseqd.inc"
