*
* $Id: sfextra.inc,v 1.3 2003/03/05 18:38:35 dpp Exp $
*
*
* $Log: sfextra.inc,v $
* Revision 1.3  2003/03/05 18:38:35  dpp
*      -> move everthing to duseq/cdscrtcd.inc
*         MUST remove include from EVERY file that uses this
*         before it can be deleted
*
* Revision 1.2  1998/07/09 01:17:30  lyon
* Added CVS tags (oops)
*
*

C*****
C*****  sfextra.inc  -- Adam L. Lyon -- 26 March 1998
C*****
C*****   Information not in regular cdscrtcd.inc and sfcom.inc common blocks
C*****   needed by SFDATA


