#!/usr/local/bin/tcsh

cd $HOME/sialignment/run/
. /nfs/cleo3/scripts/cleo3defs
c3rel cleo3_Pass2_Oct09_2001

#  OSAGENT_PORT=31416
#  export OSAGENT_PORT
#  C3_CONST=/nfs/c3con/ccon3/constants/Codi
#  export C3_CONST

suez -q > $USER_TMP/layer4.log << EOF

default prompt off

module sel CorbaModule
corba init
module sel ConstantsModule
constants in \$env(C3_CONST) meta Offline MetaListRetrieval exclude_streams svalignment
constants in \$env(C3_CONST) meta CesrOffset MetaListRetrieval
constants in \$env(C3_CONST) meta BaseGeometry MetaListRetrieval
constants in $env(C3_CONST) meta SVHybridEfficiency MetaListRetrieval

source_format sel AsciiSourceFormat
file in \$env(C3_DATA)/material.asc basegeometry

prod sel CDOffCal
prod sel SiGeom
prod sel ASiStorePro
prod sel IRGeomProd
prod sel DRGeom
prod sel ADRGeomProd
prod sel DRHitCorrectorProd
prod sel TrackDeliveryProd
prod sel SeedToTRTrackProd
prod sel NavigationProd

prod sel MagFieldProd
param MagFieldProd alwaysUseDefault true

source_format sel PDSSourceFormat
source create pdschain
file add pdschain ../loose_tracks/dual_chi_newalignment_loose1.pds beginrun startrun event
file add pdschain ../loose_tracks/dual_chi_newalignment_loose2.pds beginrun startrun event
file add pdschain ../loose_tracks/dual_chi_newalignment_loose3.pds beginrun startrun event
file add pdschain ../loose_tracks/dual_chi_newalignment_loose4.pds beginrun startrun event
file add pdschain ../loose_tracks/dual_chi_newalignment_loose5.pds beginrun startrun event
file add pdschain ../loose_tracks/dual_chi_newalignment_loose6.pds beginrun startrun event
file add pdschain ../loose_tracks/dual_chi_newalignment_loose7.pds beginrun startrun event
file add pdschain ../loose_tracks/dual_chi_newalignment_loose8.pds beginrun startrun event
file add pdschain ../loose_tracks/dual_chi_newalignment_loose9.pds beginrun startrun event
source activate pdschain beginrun startrun event

emptysource def svalignment svalignment

module sel ../build_SunOS/shlib/EnderSiAlignmentMod
param EnderSiAlignmentMod target_hits 100000

param EnderSiAlignmentMod global_init loose.svalignmentglobal
param EnderSiAlignmentMod layer_init  data8_repass2.svalignmentlayer
param EnderSiAlignmentMod ladder_init data8_repass2.svalignmentladder
param EnderSiAlignmentMod sensor_init data8_repass2.svalignmentsensor

param EnderSiAlignmentMod file_output "layer-summary4.log"

param EnderSiAlignmentMod device "layer"
param EnderSiAlignmentMod number 4

param EnderSiAlignmentMod rphi_cut 0.00012
param EnderSiAlignmentMod z_cut 0.0011

param EnderSiAlignmentMod rphi_norm 0.0013
param EnderSiAlignmentMod z_norm 0.0053

param EnderSiAlignmentMod deltaX_step 0.000050
param EnderSiAlignmentMod deltaY_step 0.000050
param EnderSiAlignmentMod deltaZ_step 0.002500
param EnderSiAlignmentMod phiX_step 0.002000
param EnderSiAlignmentMod phiY_step 0.005000
param EnderSiAlignmentMod phiZ_step 0.001000

report level NOTICE
iterator go

exit

EOF
