#!/usr/local/bin/tcsh

cd $HOME/findbug_svhits/run
. /nfs/cleo3/scripts/cleo3defs
c3rel cleo3_Nov08_2001

#  OSAGENT_PORT=31416
#  export OSAGENT_PORT
#  C3_CONST=/nfs/c3con/ccon3/constants/Codi
#  export C3_CONST

USER_HISTOGRAM_FILE=fb_fittorphi_septalign.rzn
export USER_HISTOGRAM_FILE
USER_FITTER=ChisqFitProd
export USER_FITTER

suez -f fittorphi_septalign.tcl > $USER_TMP/fb_fittorphi_septalign.log
