*
* $Id: qdcom.inc,v 1.1.1.1 1998/02/06 19:11:49 dpp Exp $
*
* $Log: qdcom.inc,v $
* Revision 1.1.1.1  1998/02/06 19:11:49  dpp
* DOIT first release.
*
* Revision 1.1.1.1  1997/04/30 12:31:25  clib
* Developmental version of DUET.
*
* Revision 1.1.1.1  1994/10/08 01:01:10  zfiles
* first version of doit in CVS
*
*
*
* qdcom.inc
*
      REAL GAIN(800)
      REAL S0(800),S1(800),S2(800),S3(800)

      COMMON /QDCOM/ GAIN,S0,S1,S2,S3
