C      Include file drmcAnodeWireEff
C
C begin_doc
C
C  $Id: drmcAnodeWireEff.inc,v 1.1 1999/09/20 22:47:17 jjo Exp $
C
C  $Log: drmcAnodeWireEff.inc,v $
C  Revision 1.1  1999/09/20 22:47:17  jjo
C  Import files into cvs
C
C
C  Documentation for include file drmcAnodeWireEff
C
C  Purpose: DR Anode wire efficiency constants
C  --------
C
C  Used in routines:
C  ----------------
C
C  Notes:
C  ------
C
C  Author:   John J O'Neill      Created:  Tue Aug 17 17:19:32 EDT 1999
C  -------
C
C  Major revisions:
C  ----------------
C
C end_doc
C
C
C  Remember NO NESTED INCLUDES (except for parameters)
C
C  COMMON BLOCK NAME should be the same as include file name!
C
C begin_var
C  variables for include file drmcAnodeWireEff:
C  -----------------------------------

C----6----------------------------------------------------------------72
C   
C  Variables contained in drmcAnodeWireEff common block
C  --------------------------------------------
 
C  end_var
C 
      COMMON/DRMCANODEWIREEFF/
C----6----------------------------------------------------------------72

      SAVE /DRMCANODEWIREEFF/



