C      Include file zdmcAnodeWireEff
C
C begin_doc
C
C
C  Documentation for include file zdmcAnodeWireEff
C
C  Purpose: ZD Anode wire efficiency constants
C  --------
C
C  Used in routines:
C  ----------------
C
C  Notes:
C  ------
C
C  Author:   Guangshun Huang      Created:  Tue Dec 17, 2002
C  -------
C
C  Major revisions:
C  ----------------
C
C end_doc
C
C
C  Remember NO NESTED INCLUDES (except for parameters)
C
C  COMMON BLOCK NAME should be the same as include file name!
C
C begin_var
C  variables for include file zdmcAnodeWireEff:
C  -----------------------------------

C----6----------------------------------------------------------------72
C   
C  Variables contained in zdmcAnodeWireEff common block
C  --------------------------------------------
 
C  end_var
C 
      COMMON/ZDMCANODEWIREEFF/
C----6----------------------------------------------------------------72

      SAVE /ZDMCANODEWIREEFF/
