*
* $Id: cdcorrdo.inc,v 1.1.1.1 1998/02/06 19:11:48 dpp Exp $
*
* $Log: cdcorrdo.inc,v $
* Revision 1.1.1.1  1998/02/06 19:11:48  dpp
* DOIT first release.
*
* Revision 1.1.1.1  1997/04/30 12:31:24  clib
* Developmental version of DUET.
*
* Revision 1.1.1.1  1994/10/08 01:01:06  zfiles
* first version of doit in CVS
*
*
* CDCORRCD - Documentation
*
* cdcorrdo.inc
*
C
* VDRFT  - Drift velocities per cylinder
* BETAW  - Beta on sense wires
* CDRFT  - Quadratic correction term
* ASAG   - Gravitational sag correction
* EBC1/4 - Vermutlich E x B corrections
* CLIGHT - Speed of light in m/psec
* VCONV  - Converts m to psec
*
* ----------------------------------------------------------
#include "doit/duseq/duseqd.inc"
