*
* $Id: cdtypecd.inc,v 1.1.1.1 1998/02/06 19:11:48 dpp Exp $
*
* $Log: cdtypecd.inc,v $
* Revision 1.1.1.1  1998/02/06 19:11:48  dpp
* DOIT first release.
*
* Revision 1.1.1.1  1997/04/30 12:31:24  clib
* Developmental version of DUET.
*
* Revision 1.1.1.1  1994/10/08 01:01:07  zfiles
* first version of doit in CVS
*
*
*CMZ :  5.54/07 17/05/91  19.19.38  by  Steve Schaffner
*CMZ :  5.53/07 22/09/90  21.14.41  by  Steve Schaffner
*CMZ :  5.52/00 24/01/90  14.44.59  by  Steve Schaffner
*-- Author :
