*
* $Id: cfxdmpd.inc,v 1.1.1.1 1998/02/06 19:11:48 dpp Exp $
*
* $Log: cfxdmpd.inc,v $
* Revision 1.1.1.1  1998/02/06 19:11:48  dpp
* DOIT first release.
*
* Revision 1.1.1.1  1997/04/30 12:31:25  clib
* Developmental version of DUET.
*
* Revision 1.2  1995/03/02 17:47:44  zfiles
* New version fro DPP. flag changes so that DUET display would work.
*
*
C CFXDMP DOCUMENTATION
C
C..CFXFTD..FLAG TO RERUN EVENT AND DUMP CFXFIT
C..CFXENT..ENTRY NUMBERS TO DUMP: RUN,EVENT,ENTRY#1,ENTRY#2
