*
* $Id: duexed.inc,v 1.1.1.1 1998/02/06 19:11:48 dpp Exp $
*
* $Log: duexed.inc,v $
* Revision 1.1.1.1  1998/02/06 19:11:48  dpp
* DOIT first release.
*
* Revision 1.1.1.1  1997/04/30 12:31:25  clib
* Developmental version of DUET.
*
* Revision 1.1.1.1  1994/10/08 01:01:07  zfiles
* first version of doit in CVS
*
*
*
* duexed.inc
*
C----------------------Executable code starts here---------------------
* ----------------------------------------------------------
#include "doit/duseq/duseqd.inc"
