*
* $Id: dupatchd.inc,v 1.1.1.1 1998/02/06 19:11:49 dpp Exp $
*
* $Log: dupatchd.inc,v $
* Revision 1.1.1.1  1998/02/06 19:11:49  dpp
* DOIT first release.
*
* Revision 1.1.1.1  1997/04/30 12:31:25  clib
* Developmental version of DUET.
*
* Revision 1.1.1.1  1994/10/08 01:01:07  zfiles
* first version of doit in CVS
*
*
*
* dupatchd.inc
*
C======================================================================
