*
* $Id: qdseq.inc,v 1.1.1.1 1998/02/06 19:11:49 dpp Exp $
*
* $Log: qdseq.inc,v $
* Revision 1.1.1.1  1998/02/06 19:11:49  dpp
* DOIT first release.
*
* Revision 1.1.1.1  1997/04/30 12:31:25  clib
* Developmental version of DUET.
*
* Revision 1.1.1.1  1994/10/08 01:01:10  zfiles
* first version of doit in CVS
*
*
*CMZ :  5.54/07 21/11/91  10.54.33  by  Steve Schaffner
*-- Author :    Brian Geiser   16/10/91
