*
* $Id: tfconspd.inc,v 1.1.1.1 1998/02/06 19:11:49 dpp Exp $
*
* $Log: tfconspd.inc,v $
* Revision 1.1.1.1  1998/02/06 19:11:49  dpp
* DOIT first release.
*
* Revision 1.1.1.1  1997/04/30 12:31:25  clib
* Developmental version of DUET.
*
* Revision 1.1.1.1  1994/10/08 01:01:08  zfiles
* first version of doit in CVS
*
*
* TFCONSPA Documentation
*
* tfconspd.inc
*
*
* PI     - Pi
* HALFPI - PI / 2.0
* TWOPI  - PI * 2.0
* RADDEG - PI / 180.0
* DEGRAD - 180.0 / PI
*
* ROOT2  - SQRT(2)
* ROOT3  - SQRT(3)
*
* AMTOMU - Meters / Microns
* PCONST - Convert curvature to GeV
* SCTGEV - Multiple scattering coefficient
*
* AMK0   - K0       mass
* AML0   - Lambda   mass
* AMEL   - Electron mass
* AMMU   - Muon     mass
* AMPI   - Pion     mass
* AMKA   - Kaon     mass
* AMPR   - Proton   mass
* AMEL2  - AMEL**2
* AMMU2  - AMMU**2
* AMPI2  - AMPI**2
* AMKA2  - AMKA**2
* AMPR2  - AMPR**2
* AML02  - AML0**2
* AMK02  - AMK0**2
C
* ----------------------------------------------------------
#include "doit/duseq/duseqd.inc"
