*
* $Id: vdhistpd.inc,v 1.1.1.1 1998/02/06 19:11:50 dpp Exp $
*
* $Log: vdhistpd.inc,v $
* Revision 1.1.1.1  1998/02/06 19:11:50  dpp
* DOIT first release.
*
* Revision 1.1.1.1  1997/04/30 12:31:26  clib
* Developmental version of DUET.
*
* Revision 1.1.1.1  1994/10/08 01:01:10  zfiles
* first version of doit in CVS
*
*
* VDHISTPAR documentation
*
* vdhistpd.inc
*
C
* NSECT1 - number of sector in bands of type 1
* NSECT2 - number of sectors in bands of type 2
* NSBAND - number of bands
* MSECN1 - number of bands of type 1
* LLYRS1 - first TF layer in band 1
* MLYRS1 - last TF layer in band 1
* LLYRS2 - first TF layer in band 2
* MLYRS2 - last TF layer in band 2
* LLYRS3 - first TF layer in band 3
* MLYRS3 - last TF layer in band 3
* LLYRS4 - first TF layer in band 4
* MLYRS4 - last TF layer in band 4
* MLBAND - maximum number of layers in any band
* NLMNS1 - minimum number of layers required in a sector in band 1
* NLMNS2 - minimum number of layers required in a sector in band 2
* NLMNS3 - minimum number of layers required in a sector in band 3
* NLMNS4 - minimum number of layers required in a sector in band 4
* ----------------------------------------------------------
#include "doit/duseq/duseqd.inc"
