*
* $Id: vdseeddo.inc,v 1.1.1.1 1998/02/06 19:11:50 dpp Exp $
*
* $Log: vdseeddo.inc,v $
* Revision 1.1.1.1  1998/02/06 19:11:50  dpp
* DOIT first release.
*
* Revision 1.1.1.1  1997/04/30 12:31:26  clib
* Developmental version of DUET.
*
* Revision 1.1.1.1  1994/10/08 01:01:10  zfiles
* first version of doit in CVS
*
*
* VDSEEDCD Documentation
*
* vdseeddo.inc
*
C
* Contains information from FVDTRK on CD seed tracks
*
* NTRKSD            - Number of VD seed tracks
* PHISD(ITRK)       - PHI of the seed track
* IADRSD(ILYR,ITRK) - Address (from IADRHW) of hit
*
* ----------------------------------------------------------
#include "doit/duseq/duseqd.inc"
