#if 0

* These parameters are called the device definition parameters
*DEVICE_DRFT  - Drift  chamber   device
*DEVICE_DRCT  - DR cathode strip device
*DEVICE_SVX1  - Silicon vertex detector first generation R-Phi
*DEVICE_SVZ1  - Silicon vertex detector first generation Z
*DEVICE_IVDT  - the "IV" ; the 3 layer Ohio straw device 
*DEVICE_VDET  - the "VD" ; the 10 layer Ohio small cell device
*DEVICE_VDCT  - "VD" cathodes 
*DEVICE_PROP  - the "IZ" ; the 3 layer Syracuse MWPC device
*DEVICE_PTLA  - the "PT" ; the 6 layer Ohio straw device 
*DEVICE_PTLC  - "PT" cathodes, although it didi not have any 
*DEVICE_ZDA   - the "ZD" ; the 6 layer Cornell open cell device
*DEVICE_TPC1  - Dan's imaginary TPC device

#endif
#define DEVICE_DRFT  1
#define DEVICE_DRCT  2
#define DEVICE_SVX1  3
#define DEVICE_SVZ1  4
#define DEVICE_IVDT  5 
#define DEVICE_VDET  6
#define DEVICE_VDCT  7
#define DEVICE_PROP  8 
#define DEVICE_PTLA  9
#define DEVICE_PTLC 10
#define DEVICE_ZDA  11 
#define DEVICE_TPC1 12 
















